### ISSUE TITLE
Null App Detected

### ISSUE THREAD

**Issue by joshuaoliver** [metabase/metabase-deploy#3]
Not sure if this is on the Heroku side, but I've tried multiple times via the button, and always getting the following.

![image](https://cloud.githubusercontent.com/assets/990076/10645453/604aa8f6-7860-11e5-96b8-1a5d3d23ec28.png)

**Comment by tlrobinson** [comment]
This is not actually an error. For this repo to speed up deployment we use a precompiled jar which doesn't require a buildpack, so we use the [null buildpack](https://github.com/ryandotsmith/null-buildpack).

FYI if you deploy from the main repo at https://github.com/metabase/metabase you need the Clojure and Node.js buildpacks.
