### ISSUE TITLE
Heroku $PORT check fails

### ISSUE THREAD

**Issue by shri** [metabase/metabase-deploy#4]
Heroku consistently gives me the following error that prevents Metabase from running:

`Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch`

Metabase successfully logs the following before this error, consistently:

`2015-10-21T19:19:17.398606+00:00 app[web.1]: 2015-10-21 19:19:17,397 [INFO ] org.eclipse.jetty.util.log :: Logging initialized @6640ms`

`2015-10-21T19:19:33.296176+00:00 app[web.1]: 2015-10-21 19:19:33,296 [INFO ] metabase.core :: Starting Metabase in STANDALONE mode`

`2015-10-21T19:19:33.335505+00:00 app[web.1]: 2015-10-21 19:19:33,335 [INFO ] metabase.db :: Verifying Database Connection ...`

`2015-10-21T19:19:33.335099+00:00 app[web.1]: 2015-10-21 19:19:33,334 [INFO ] metabase.core :: Starting Metabase version v0.12.0 (32ac4fd master)...`

`2015-10-21T19:19:34.334109+00:00 app[web.1]: 2015-10-21 19:19:34,333 [INFO ] metabase.db :: Verify Database Connection ... CHECK`

I'm having Heroku change the $PORT check time to 120 seconds and will report back.

**Comment by shri** [comment]
Update--still happens after 120 seconds, now I get:

`Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 120 seconds of launch`

**Comment by tlrobinson** [comment]
Please use this issue: https://github.com/metabase/metabase/issues/1311 We're probably going to disable GitHub Issues on this repository.
